encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/", views.random_entry, name="random_entry"),
    path("delete", views.delete, name="delete"),
    path("search", views.search, name="search")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

from .util import save_entry, get_entry, list_entries

class NewEntryForm(forms.Form):
    title = forms.CharField(
        label="title",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Title',
                'style': 'width: 10cm',
                'autocomplete': 'off'
            }
        ),
        help_text='Please use "_" instead of spaces for the title.'
    )
    content = forms.CharField(
        label="content",
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Input entry content here.',
                'style': 'width: 90%'
            }
        )
    )
    
class SearchForm(forms.Form):
    item = forms.CharField(
        label="title", 
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search Encyclopedia',
                'style': 'width: 100%; height: 10%;',
                'autocomplete': 'off'
            }
        )
    )

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.files.storage import default_storage
from markdown2 import Markdown
import random


from .util import save_entry, get_entry, list_entries
from .forms import NewEntryForm, SearchForm

markdown = Markdown()

# DONE
def index(request):
    """Show a list of existing entries"""

    return render(request, "encyclopedia/index.html", {
        "entries": list_entries(),
        "search_form": SearchForm()
    })
###

# DONE
def entry(request, title):
    """Display a selected entry page"""
    
    entries = []
    if not title:
        return render(request, "encyclopedia/search_error.html", {
            "title": "no_title",
            "entries": entries,
            "search_form": SearchForm()
        })

    for entry_title in list_entries():
        if entry_title.lower() == title.lower():
            content = markdown.convert(get_entry(entry_title))

            return render(request, "encyclopedia/entry.html", {
                "entry_title": title,
                "entry_content": content,
                "search_form": SearchForm()
            })

        elif title.lower() in entry_title.lower():
                entries.append(entry_title)

    # List related entry searches if no match is found
    return render(request, "encyclopedia/search_error.html", {
            "entry_title": title,
            "entries": entries,
            "search_form": SearchForm()
        })
###

# DONE
def new(request):
    """Add a new entry to memory"""

    # request method is "POST"
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        
        if form.is_valid():
            content = form.cleaned_data["content"]
            title = form.cleaned_data["title"]
            
            for entry_title in list_entries():
                if entry_title.lower() == title.lower():
                    return render(request, "encyclopedia/new_error.html", {
                        "heading": "Add New Entry",
                        "error": f'"{title}" already exists as "{entry_title}"',
                        "form": NewEntryForm
                    })
            
            save_entry(title, content)
            
            content = markdown.convert(content)

            return render(request, "encyclopedia/entry.html", {
                "entry_content": content,
                "entry_title": title,
                "search_form": SearchForm()
            })
            
        else:
            return render(request, "encyclopedia/new_error.html", {
                "heading": "Add New Entry",
                'error': 'Please fill "Title" and "Content" input fields.',
                "form": NewEntryForm,
                "search_form": SearchForm()
            })

    # request method is "GET"
    else:
        return render(request, "encyclopedia/new.html", {
            "heading": "Add New Entry",
            "form": NewEntryForm,
            "search_form": SearchForm()
        })
####

# DONE
def edit(request, title):
    """Edit an existing entry"""

    entry_title0 = title

    # request method is "GET"
    if request.method == "GET":
        content = get_entry(entry_title0)

        form = NewEntryForm(
            initial={
                'content': content
            })

        form.fields["title"].widget = forms.HiddenInput()
        form.fields["title"].required = False

        return render(request, "encyclopedia/edit.html", {
            "heading": "Edit Entry",
            'form': form,
            "entry_title": entry_title0,
            "search_form": SearchForm()
        })
    
    # request method is "POST"
    else:
        form = NewEntryForm(request.POST)

        form.fields["title"].required = False

        if form.is_valid():
            content = form.cleaned_data["content"]
            
            save_entry(title, content)

            content = markdown.convert(get_entry(title))

            return render(request, "encyclopedia/entry.html", {
                "entry_title": title,
                "entry_content": content,
                "search_form": SearchForm()
            })
            
        else:
            form = NewEntryForm()
            form.fields["title"].widget = forms.HiddenInput()

            return render(request, "encyclopedia/edit_error.html", {
                "heading": "Edit Entry",
                'error': 'Please fill "Content" input field.',
                "entry_title": entry_title0,
                "form": form,
                "search_form": SearchForm()
            })
###
    
#DONE
def random_entry(request):
    """Get a random entry page"""
    
    entry_title = random.choice(list_entries())
    content = markdown.convert(get_entry(entry_title))

    return render(request, "encyclopedia/entry.html", {
        "entry_title": entry_title,
        "entry_content": content,
        "search_form": SearchForm()
    })
###

# DONE
def delete(request):
    """Delete an entry from memory"""

    title1 = request.GET.get('d')
    if title1:
        filename = f"entries/{title1}.md"
        if default_storage.exists(filename):
            default_storage.delete(filename)
            return HttpResponseRedirect(reverse('wiki:index'))
###

# DONE
def search(request):
    """Search for an entry by keywords 
    via a form
    """ 
    form = SearchForm(request.POST)

    if form.is_valid():
        item = form.cleaned_data["item"]
        entries = []

        for entry_title in list_entries():
            if item.lower() == entry_title.lower():
                content = markdown.convert(get_entry(entry_title))
                
                return render(request, "encyclopedia/entry.html", {
                    "entry_content": content,
                    "entry_title": entry_title,
                    "search_form": SearchForm()
                })

            elif item.lower() in entry_title.lower():
                entries.append(entry_title)

        if not entries:
            return render(request, "encyclopedia/search_error.html", {
                "entry_title": item,
                "search_form": SearchForm()
            })
        
        return render(request, "encyclopedia/search.html", {
            "entry_title": item,
            "entries": entries,
            "search_form": SearchForm()
        })
###
            
            

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% load widget_tweaks %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <body>
        <h1>{{ heading }}</h1>
        <hr>
        <h2>Entry title: <i>{{ entry_title }}</i></h2>
        <form method="post" novalidate>
            {% csrf_token %}

            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in form.non_field_errors %}
                    {{ error }}
                    {% endfor %}
                </div>
            {% endif %}

            {% for field in form.visible_fields %}
                <div class="form-group">
                    {{ field.label_tag }}

                    {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                    {% else %}
                    {% render_field field class="form-control" %}
                    {% endif %}

                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-outline-success">Save Changes</button>
        </form>
    </body>
{% endblock %}

encyclopedia/templates/encyclopedia/edit_error.html
{% extends "encyclopedia/layout.html" %}

{% load widget_tweaks %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>{{ heading }}</h1>
    <hr>
    <h2>{{ entry_title }}</h2>
    {% if error is not "False"%}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    <form method="post" novalidate>
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-outline-primary">Submit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% load widget_tweaks %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <style>
        p {
            width: 98%;
        }

        #btn-dlt {
            margin-top: 20px;
        }

        .eb {
            margin-top: 20px;
        }
    </style>

    <body>
        <p>{{ entry_content|safe }}</p>
        <a href=/edit/{{ entry_title }} role="button" class="btn btn-outline-info btn-sm eb">Edit Entry</a>
        <form action={% url 'wiki:delete' %}>
            <button type="submit" id="btn-dlt" class="btn btn-outline-danger btn-sm" name="d" value="{{ entry_title }}">Delete Entry</button>
        </form>
    </body>
    
    
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>All Pages</h1>
    <hr>
    <ul>
        {% for entry in entries %}
            <li>
                <a href=/wiki/{{ entry }} role="button" class="btn btn-link">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

{% load widget_tweaks %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <style>
            #search_button {
                background-color: rgba(204, 204, 204, 0.8);
                width: 100%;
                height: 20px;
                margin-top: 15px;
                margin-bottom: 20px;
                justify-content: center;
                display: flex;
                padding: 0cm;

                font-size: 10px;
                font-family: Arial, Helvetica, sans-serif;
                color: black;

                border-color: black;
                border-radius: 3px;
                border-style: solid;
                border-width: 0.02cm;
            }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="POST" action={% url 'wiki:search' %}>
                    {% csrf_token %}
                        {{ search_form.item }}
                    <div>
                        <input type="submit" class="btn btn-primary btn-sm" id="search_button" value="Search">
                    </div>
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}" class="btn btn-link">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}" class="btn btn-link btn-sm text-nowrap">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_entry' %}" class="btn btn-link btn-sm">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9 entry">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% load widget_tweaks %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>{{ heading }}</h1>
    <form method="post" novalidate>
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
        {   { hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
            <button type="submit" class="btn btn-outline-primary">Submit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/new_error.html
{% extends "encyclopedia/layout.html" %}

{% load widget_tweaks %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Add New Entry</h1>
    {% if error is not "False"%}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    <form method="post" novalidate>
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-outline-primary">Submit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% load widget_tweaks %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <body>
        {% if title != "no_title" %}
            <h1>Showing results for "{{ entry_title }}"</h1>
            <hr>
            <ul>
                {% for entry in entries %}
                    <li>
                        <a type="submit" href=/wiki/{{ entry }} class="btn btn-link btn-small">{{ entry }}</a>
                    </li>
                    {% empty %}
                    <h4 style="color: rgba(255, 47, 47, 0.767);">No Similar Results.</h4>
                {% endfor %}
            </ul>
        {% endif %}
    </body>
    
{% endblock %}

encyclopedia/templates/encyclopedia/search_error.html
{% extends "encyclopedia/layout.html" %}

{% load widget_tweaks %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <body>
        {% if title != "no_title" %}
            <h1>"{{ entry_title }}" Not Found.</h1>
            <hr>
            <h3>Similar results:</h3>
            <ul>
                {% for entry in entries %}
                    <li>
                        <a type="submit" href=/wiki/{{ entry }} class="btn btn-link btn-small">{{ entry }}</a>
                    </li>
                    {% empty %}
                    <h4 style="color: rgba(255, 47, 47, 0.767);">No Similar Results.</h4>
                {% endfor %}
            </ul>
        {% endif %}
    </body>
    
{% endblock %}